<?php
$labels = array();
$labels['plugin_manager_title'] = 'Мениджър на плъгини';
$labels['plugin_manager_desc'] = 'Проверява инсталираните приставки на Roundcube и проверява за актуализации.';
$labels['plugin'] = 'Плъгин';
$labels['directory'] = 'Директория';
$labels['enabled'] = 'Разрешено';
$labels['disabled'] = 'Инвалиди';
$labels['version_local'] = 'Местна версия';
$labels['version_remote'] = 'Последна версия';
$labels['status'] = 'Статус';
$labels['actions'] = 'Действия';
$labels['unknown'] = 'неизвестен';
$labels['up_to_date'] = 'Актуално';
$labels['update_available'] = 'Налична е актуализация';
$labels['not_checked'] = 'Не е проверено';
$labels['refresh'] = 'Обновяване';
$labels['toggle_remote'] = 'Активиране на дистанционни проверки';
$labels['disable_remote'] = 'Деактивиране на дистанционните проверки';
$labels['enable_remote'] = 'Активиране на дистанционни проверки';
$labels['remote_off_notice'] = 'Дистанционните проверки са деактивирани!';
$labels['sources'] = 'Източници';
$labels['packagist'] = 'Packagist';
$labels['github'] = 'GitHub';
$labels['pm_yes'] = 'Да';
$labels['pm_no'] = 'Не';
?>
