<?php
$labels = array();
$labels['plugin_manager_title'] = 'Správce zásuvných modulů';
$labels['plugin_manager_desc'] = 'Kontroluje nainstalované zásuvné moduly Roundcube a zjišťuje aktualizace.';
$labels['plugin'] = 'Zásuvný modul';
$labels['directory'] = 'Adresář';
$labels['enabled'] = 'Povoleno';
$labels['disabled'] = 'Bezbariérový';
$labels['version_local'] = 'Místní verze';
$labels['version_remote'] = 'Nejnovější verze';
$labels['status'] = 'Stav';
$labels['actions'] = 'Akce';
$labels['unknown'] = 'neznámý';
$labels['up_to_date'] = 'Aktuální';
$labels['update_available'] = 'K dispozici je aktualizace';
$labels['not_checked'] = 'Nebylo zkontrolováno';
$labels['refresh'] = 'Obnovit';
$labels['toggle_remote'] = 'Povolení vzdálených kontrol';
$labels['disable_remote'] = 'Zakázat vzdálené kontroly';
$labels['enable_remote'] = 'Povolení vzdálených kontrol';
$labels['remote_off_notice'] = 'Vzdálené kontroly jsou zakázány!';
$labels['sources'] = 'Zdroje';
$labels['packagist'] = 'Packagist';
$labels['github'] = 'GitHub';
$labels['pm_yes'] = 'Ano';
$labels['pm_no'] = 'Ne';
$labels['updateall'] = 'Aktualizace všech zásuvných modulů';
?>
