<?php
$labels = array();
$labels['plugin_manager_title'] = 'Plugin-manager';
$labels['plugin_manager_desc'] = 'Undersøger installerede Roundcube-plugins og tjekker for opdateringer.';
$labels['plugin'] = 'Plugin';
$labels['directory'] = 'Vejviser';
$labels['enabled'] = 'Aktiveret';
$labels['disabled'] = 'Handicappet';
$labels['version_local'] = 'Lokal version';
$labels['version_remote'] = 'Seneste version';
$labels['status'] = 'Status';
$labels['actions'] = 'Handlinger';
$labels['unknown'] = 'ukendt';
$labels['up_to_date'] = 'Op til dato';
$labels['update_available'] = 'Opdatering tilgængelig';
$labels['not_checked'] = 'Ikke kontrolleret';
$labels['refresh'] = 'Opdatering';
$labels['toggle_remote'] = 'Aktivér fjernkontrol';
$labels['disable_remote'] = 'Slå fjernkontrol fra';
$labels['enable_remote'] = 'Aktivér fjernkontrol';
$labels['remote_off_notice'] = 'Fjernkontrol er deaktiveret!';
$labels['sources'] = 'Kilder';
$labels['packagist'] = 'Pakkeleverandør';
$labels['github'] = 'GitHub';
$labels['pm_yes'] = 'Ja';
$labels['pm_no'] = 'Nej';
$labels['updateall'] = 'Opdater alle plugins';
?>
