<?php
$labels = array();
$labels['plugin_manager_title'] = 'Plugin-Manager';
$labels['plugin_manager_desc'] = 'Überprüft die installierten Roundcube-Plugins und sucht nach Updates.';
$labels['plugin'] = 'Plugin';
$labels['directory'] = 'Verzeichnis';
$labels['enabled'] = 'Aktiviert';
$labels['disabled'] = 'Behinderte';
$labels['version_local'] = 'Lokale Version';
$labels['version_remote'] = 'Letzte Version';
$labels['status'] = 'Status';
$labels['actions'] = 'Aktionen';
$labels['unknown'] = 'unbekannt';
$labels['up_to_date'] = 'Aktualität';
$labels['update_available'] = 'Update verfügbar';
$labels['not_checked'] = 'Nicht geprüft';
$labels['refresh'] = 'Auffrischen';
$labels['toggle_remote'] = 'Aktivieren von Fernprüfungen';
$labels['disable_remote'] = 'Fernprüfungen deaktivieren';
$labels['enable_remote'] = 'Aktivieren von Fernprüfungen';
$labels['remote_off_notice'] = 'Fernprüfungen sind deaktiviert!';
$labels['sources'] = 'Quellen';
$labels['packagist'] = 'Packagist';
$labels['github'] = 'GitHub';
$labels['pm_yes'] = 'Ja';
$labels['pm_no'] = 'Nein';
$labels['updateall'] = 'Alle Plugins aktualisieren';
?>
