<?php
$labels = array();
$labels['plugin_manager_title'] = 'Διαχειριστής πρόσθετων';
$labels['plugin_manager_desc'] = 'Ελέγξτε τα εγκατεστημένα πρόσθετα Roundcube και ελέγξτε για ενημερώσεις.';
$labels['plugin'] = 'Plugin';
$labels['directory'] = 'Κατάλογος';
$labels['enabled'] = 'Ενεργοποιημένο';
$labels['version_local'] = 'Τοπική έκδοση';
$labels['version_remote'] = 'Τελευταία έκδοση';
$labels['status'] = 'Κατάσταση';
$labels['actions'] = 'Δράσεις';
$labels['unknown'] = 'unknown';
$labels['up_to_date'] = 'Μέχρι σήμερα';
$labels['update_available'] = 'Διαθέσιμη ενημέρωση';
$labels['not_checked'] = 'Δεν έχει ελεγχθεί';
$labels['refresh'] = 'Ανανέωση';
$labels['toggle_remote'] = 'Ενεργοποίηση απομακρυσμένων ελέγχων';
$labels['disable_remote'] = 'Απενεργοποίηση απομακρυσμένων ελέγχων';
$labels['remote_off_notice'] = 'Οι απομακρυσμένοι έλεγχοι είναι απενεργοποιημένοι.';
$labels['enable_remote'] = 'Ενεργοποίηση απομακρυσμένων ελέγχων';
$labels['sources'] = 'Πηγές';
$labels['packagist'] = 'Συσκευαστής';
$labels['github'] = 'GitHub';
?>
