<?php
$labels = array();
$labels['plugin_manager_title'] = 'Plugin Manager';
$labels['plugin_manager_desc'] = 'Inspects installed Roundcube plugins and check for updates.';
$labels['plugin'] = 'Plugin';
$labels['directory'] = 'Directory';
$labels['enabled'] = 'Enabled';
$labels['disabled'] = 'Disabled';
$labels['version_local'] = 'Local version';
$labels['version_remote'] = 'Latest version';
$labels['status'] = 'Status';
$labels['actions'] = 'Actions';
$labels['unknown'] = 'unknown';
$labels['up_to_date'] = 'Up to date';
$labels['update_available'] = 'Update available';
$labels['not_checked'] = 'Not checked';
$labels['refresh'] = 'Refresh';
$labels['toggle_remote'] = 'Enable remote checks';
$labels['disable_remote'] = 'Disable remote checks';
$labels['enable_remote'] = 'Enable remote checks';
$labels['remote_off_notice'] = 'Remote checks are Disabled!';
$labels['sources'] = 'Sources';
$labels['packagist'] = 'Packagist';
$labels['github'] = 'GitHub';
$labels['pm_yes'] = 'Yes';
$labels['pm_no'] = 'No';
$labels['updateall'] = 'Update All Plugins';
?>
