<?php
$labels = array();
$labels['plugin_manager_title'] = 'Plugin Manager';
$labels['plugin_manager_desc'] = 'Kontrollige paigaldatud Roundcube\'i pistikprogramme ja kontrollige, kas need on uuendatud.';
$labels['plugin'] = 'Plugin';
$labels['directory'] = 'Kataloog';
$labels['enabled'] = 'Lubatud';
$labels['version_local'] = 'Kohalik versioon';
$labels['version_remote'] = 'Viimane versioon';
$labels['status'] = 'Staatus';
$labels['actions'] = 'Meetmed';
$labels['unknown'] = 'unknown';
$labels['up_to_date'] = 'Kuni tänaseni';
$labels['update_available'] = 'Saadaval on värskendus';
$labels['not_checked'] = 'Ei ole kontrollitud';
$labels['refresh'] = 'Värskenda';
$labels['toggle_remote'] = 'Kaugkontrollide lubamine';
$labels['disable_remote'] = 'Kaugkontrollide keelamine';
$labels['remote_off_notice'] = 'Kaugkontrollid on välja lülitatud.';
$labels['enable_remote'] = 'Kaugkontrollide lubamine';
$labels['sources'] = 'Allikad';
$labels['packagist'] = 'Pakendaja';
$labels['github'] = 'GitHub';
?>
