<?php
$labels = array();
$labels['plugin_manager_title'] = 'Plugin Manager';
$labels['plugin_manager_desc'] = 'Tarkistaa asennetut Roundcube-liitännäiset ja tarkistaa päivitykset.';
$labels['plugin'] = 'Plugin';
$labels['directory'] = 'Hakemisto';
$labels['enabled'] = 'Käytössä';
$labels['disabled'] = 'Vammaiset';
$labels['version_local'] = 'Paikallinen versio';
$labels['version_remote'] = 'Uusin versio';
$labels['status'] = 'Tila';
$labels['actions'] = 'Toimet';
$labels['unknown'] = 'tuntematon';
$labels['up_to_date'] = 'Ajan tasalla';
$labels['update_available'] = 'Päivitys saatavilla';
$labels['not_checked'] = 'Ei tarkistettu';
$labels['refresh'] = 'Päivitä';
$labels['toggle_remote'] = 'Ota etätarkastukset käyttöön';
$labels['disable_remote'] = 'Etätarkastusten poistaminen käytöstä';
$labels['enable_remote'] = 'Ota etätarkastukset käyttöön';
$labels['remote_off_notice'] = 'Etätarkistukset on poistettu käytöstä!';
$labels['sources'] = 'Lähteet';
$labels['packagist'] = 'Packagist';
$labels['github'] = 'GitHub';
$labels['pm_yes'] = 'Kyllä';
$labels['pm_no'] = 'Ei';
$labels['updateall'] = 'Päivitä kaikki lisäosat';
?>
