<?php
$labels = array();
$labels['plugin_manager_title'] = 'Gestionnaire de plugins';
$labels['plugin_manager_desc'] = 'Inspecte les plugins Roundcube installés et vérifie s\'il y a des mises à jour.';
$labels['plugin'] = 'Plugin';
$labels['directory'] = 'Annuaire';
$labels['enabled'] = 'Activé';
$labels['disabled'] = 'Handicapés';
$labels['version_local'] = 'Version locale';
$labels['version_remote'] = 'Dernière version';
$labels['status'] = 'Statut';
$labels['actions'] = 'Actions';
$labels['unknown'] = 'inconnue';
$labels['up_to_date'] = 'A jour';
$labels['update_available'] = 'Mise à jour disponible';
$labels['not_checked'] = 'Non vérifié';
$labels['refresh'] = 'Rafraîchir';
$labels['toggle_remote'] = 'Activer les contrôles à distance';
$labels['disable_remote'] = 'Désactiver les contrôles à distance';
$labels['enable_remote'] = 'Activer les contrôles à distance';
$labels['remote_off_notice'] = 'Les contrôles à distance sont désactivés !';
$labels['sources'] = 'Sources d\'information';
$labels['packagist'] = 'Packagiste';
$labels['github'] = 'GitHub';
$labels['pm_yes'] = 'Oui';
$labels['pm_no'] = 'Non';
$labels['updateall'] = 'Mise à jour de tous les plugins';
?>
