<?php
$labels = array();
$labels['plugin_manager_title'] = 'Plugin menedzser';
$labels['plugin_manager_desc'] = 'Ellenőrzi a telepített Roundcube bővítményeket és ellenőrzi a frissítéseket.';
$labels['plugin'] = 'Plugin';
$labels['directory'] = 'Címtár';
$labels['enabled'] = 'Engedélyezve';
$labels['disabled'] = 'Mozgáskorlátozottak';
$labels['version_local'] = 'Helyi változat';
$labels['version_remote'] = 'Legújabb verzió';
$labels['status'] = 'Állapot';
$labels['actions'] = 'Tevékenységek';
$labels['unknown'] = 'unknown';
$labels['up_to_date'] = 'Naprakész';
$labels['update_available'] = 'Frissítés elérhető';
$labels['not_checked'] = 'Nem ellenőrizve';
$labels['refresh'] = 'Frissítés';
$labels['toggle_remote'] = 'Távoli ellenőrzések engedélyezése';
$labels['disable_remote'] = 'Távoli ellenőrzések letiltása';
$labels['enable_remote'] = 'Távoli ellenőrzések engedélyezése';
$labels['remote_off_notice'] = 'A távoli ellenőrzések letiltva!';
$labels['sources'] = 'Források';
$labels['packagist'] = 'Csomagoló';
$labels['github'] = 'GitHub';
$labels['pm_yes'] = 'Igen';
$labels['pm_no'] = 'Nem';
?>
