<?php
$labels = array();
$labels['plugin_manager_title'] = 'プラグインマネージャー';
$labels['plugin_manager_desc'] = 'インストールされているRoundcubeプラグインを検査し、更新をチェックします。';
$labels['plugin'] = 'プラグイン';
$labels['directory'] = 'ディレクトリ';
$labels['enabled'] = '有効';
$labels['disabled'] = '無効';
$labels['version_local'] = 'ローカル版';
$labels['version_remote'] = '最新バージョン';
$labels['status'] = 'ステータス';
$labels['actions'] = '行動';
$labels['unknown'] = '不明';
$labels['up_to_date'] = '最新情報';
$labels['update_available'] = '更新あり';
$labels['not_checked'] = '未確認';
$labels['refresh'] = 'リフレッシュ';
$labels['toggle_remote'] = 'リモートチェックを有効にする';
$labels['disable_remote'] = 'リモートチェックを無効にする';
$labels['enable_remote'] = 'リモートチェックを有効にする';
$labels['remote_off_notice'] = 'リモートチェックは無効！';
$labels['sources'] = '情報源';
$labels['packagist'] = 'パッカジスト';
$labels['github'] = 'ギットハブ';
$labels['pm_yes'] = 'はい';
$labels['pm_no'] = 'いいえ';
$labels['updateall'] = 'すべてのプラグインを更新する';
?>
