<?php
$labels = array();
$labels['plugin_manager_title'] = '플러그인 관리자';
$labels['plugin_manager_desc'] = '설치된 라운드큐브 플러그인을 검사하고 업데이트를 확인합니다.';
$labels['plugin'] = '플러그인';
$labels['directory'] = '디렉토리';
$labels['enabled'] = '활성화됨';
$labels['disabled'] = '장애인';
$labels['version_local'] = '로컬 버전';
$labels['version_remote'] = '최신 버전';
$labels['status'] = '상태';
$labels['actions'] = '작업';
$labels['unknown'] = '알 수 없음';
$labels['up_to_date'] = '최신 정보';
$labels['update_available'] = '업데이트 가능';
$labels['not_checked'] = '확인되지 않음';
$labels['refresh'] = '새로 고침';
$labels['toggle_remote'] = '원격 확인 사용';
$labels['disable_remote'] = '원격 확인 비활성화';
$labels['enable_remote'] = '원격 확인 사용';
$labels['remote_off_notice'] = '원격 확인이 비활성화되었습니다!';
$labels['sources'] = '출처';
$labels['packagist'] = 'Packagist';
$labels['github'] = 'GitHub';
$labels['pm_yes'] = '예';
$labels['pm_no'] = '아니요';
$labels['updateall'] = '모든 플러그인 업데이트';
?>
