<?php
$labels = array();
$labels['plugin_manager_title'] = 'Įskiepių tvarkyklė';
$labels['plugin_manager_desc'] = 'Patikrinkite įdiegtus "Roundcube" įskiepius ir patikrinkite, ar yra atnaujinimų.';
$labels['plugin'] = 'Įskiepis';
$labels['directory'] = 'Katalogas';
$labels['enabled'] = 'Įjungta';
$labels['version_local'] = 'Vietinė versija';
$labels['version_remote'] = 'Naujausia versija';
$labels['status'] = 'Statusas';
$labels['actions'] = 'Veiksmai';
$labels['unknown'] = 'nežinomas';
$labels['up_to_date'] = 'Atnaujinta';
$labels['update_available'] = 'Galimas atnaujinimas';
$labels['not_checked'] = 'Nepatikrinta';
$labels['refresh'] = 'Atnaujinti';
$labels['toggle_remote'] = 'Įgalinti nuotolinius patikrinimus';
$labels['disable_remote'] = 'Išjungti nuotolinius patikrinimus';
$labels['remote_off_notice'] = 'Nuotoliniai patikrinimai yra išjungti.';
$labels['enable_remote'] = 'Įgalinti nuotolinius patikrinimus';
$labels['sources'] = 'Šaltiniai';
$labels['packagist'] = 'Packagist';
$labels['github'] = '"GitHub"';
?>
