<?php
$labels = array();
$labels['plugin_manager_title'] = 'Spraudņu pārvaldnieks';
$labels['plugin_manager_desc'] = 'Pārbauda instalētos Roundcube spraudņus un pārbauda, vai nav atjauninājumu.';
$labels['plugin'] = 'Spraudnis';
$labels['directory'] = 'Katalogs';
$labels['enabled'] = 'Ieslēgts';
$labels['disabled'] = 'Invalīdi';
$labels['version_local'] = 'Vietējā versija';
$labels['version_remote'] = 'Jaunākā versija';
$labels['status'] = 'Statuss';
$labels['actions'] = 'Darbības';
$labels['unknown'] = 'nezināms';
$labels['up_to_date'] = 'Aktualizēts';
$labels['update_available'] = 'Pieejams atjauninājums';
$labels['not_checked'] = 'Nav pārbaudīts';
$labels['refresh'] = 'Atjaunināt';
$labels['toggle_remote'] = 'Iespējot attālinātās pārbaudes';
$labels['disable_remote'] = 'Attālo pārbaužu atspējošana';
$labels['enable_remote'] = 'Iespējot attālinātās pārbaudes';
$labels['remote_off_notice'] = 'Attālinātās pārbaudes ir atspējotas!';
$labels['sources'] = 'Avoti';
$labels['packagist'] = 'Iepakotājs';
$labels['github'] = 'GitHub';
$labels['pm_yes'] = 'Jā';
$labels['pm_no'] = 'Nē';
?>
