<?php
$labels = array();
$labels['plugin_manager_title'] = 'Menedżer wtyczek';
$labels['plugin_manager_desc'] = 'Sprawdza zainstalowane wtyczki Roundcube i sprawdza dostępność aktualizacji.';
$labels['plugin'] = 'Wtyczka';
$labels['directory'] = 'Katalog';
$labels['enabled'] = 'Włączone';
$labels['disabled'] = 'Wyłączony';
$labels['version_local'] = 'Wersja lokalna';
$labels['version_remote'] = 'Najnowsza wersja';
$labels['status'] = 'Status';
$labels['actions'] = 'Działania';
$labels['unknown'] = 'nieznany';
$labels['up_to_date'] = 'Aktualny';
$labels['update_available'] = 'Aktualizacja dostępna';
$labels['not_checked'] = 'Nie zaznaczono';
$labels['refresh'] = 'Odświeżanie';
$labels['toggle_remote'] = 'Włącz zdalne kontrole';
$labels['disable_remote'] = 'Wyłącz zdalne kontrole';
$labels['enable_remote'] = 'Włącz zdalne kontrole';
$labels['remote_off_notice'] = 'Zdalne kontrole są wyłączone!';
$labels['sources'] = 'Źródła';
$labels['packagist'] = 'Packagist';
$labels['github'] = 'GitHub';
$labels['pm_yes'] = 'Tak';
$labels['pm_no'] = 'Nie';
?>
