<?php
$labels = array();
$labels['plugin_manager_title'] = 'Manager de pluginuri';
$labels['plugin_manager_desc'] = 'Inspectează pluginurile Roundcube instalate și verifică dacă există actualizări.';
$labels['plugin'] = 'Plugin';
$labels['directory'] = 'Director';
$labels['enabled'] = 'Activat';
$labels['disabled'] = 'Dezactivat';
$labels['version_local'] = 'Versiunea locală';
$labels['version_remote'] = 'Cea mai recentă versiune';
$labels['status'] = 'Statut';
$labels['actions'] = 'Acțiuni';
$labels['unknown'] = 'necunoscut';
$labels['up_to_date'] = 'La zi';
$labels['update_available'] = 'Actualizare disponibilă';
$labels['not_checked'] = 'Nu a fost verificat';
$labels['refresh'] = 'Reîmprospătare';
$labels['toggle_remote'] = 'Activarea verificărilor la distanță';
$labels['disable_remote'] = 'Dezactivarea verificărilor la distanță';
$labels['enable_remote'] = 'Activarea verificărilor la distanță';
$labels['remote_off_notice'] = 'Verificările la distanță sunt dezactivate!';
$labels['sources'] = 'Surse';
$labels['packagist'] = 'Packagist';
$labels['github'] = 'GitHub';
$labels['pm_yes'] = 'Da';
$labels['pm_no'] = 'Nu';
?>
