<?php
$labels = array();
$labels['plugin_manager_title'] = 'Správca zásuvných modulov';
$labels['plugin_manager_desc'] = 'Kontroluje nainštalované doplnky Roundcube a kontroluje ich aktualizácie.';
$labels['plugin'] = 'Plugin';
$labels['directory'] = 'Adresár';
$labels['enabled'] = 'Povolené';
$labels['disabled'] = 'Bezbariérový';
$labels['version_local'] = 'Miestna verzia';
$labels['version_remote'] = 'Najnovšia verzia';
$labels['status'] = 'Stav';
$labels['actions'] = 'Činnosti';
$labels['unknown'] = 'neznáme';
$labels['up_to_date'] = 'Aktuálne';
$labels['update_available'] = 'K dispozícii je aktualizácia';
$labels['not_checked'] = 'Nekontrolované';
$labels['refresh'] = 'Obnoviť';
$labels['toggle_remote'] = 'Povolenie vzdialených kontrol';
$labels['disable_remote'] = 'Zakázať vzdialené kontroly';
$labels['enable_remote'] = 'Povolenie vzdialených kontrol';
$labels['remote_off_notice'] = 'Vzdialené kontroly sú zakázané!';
$labels['sources'] = 'Zdroje';
$labels['packagist'] = 'Packagist';
$labels['github'] = 'GitHub';
$labels['pm_yes'] = 'Áno';
$labels['pm_no'] = 'Nie';
$labels['updateall'] = 'Aktualizácia všetkých zásuvných modulov';
?>
