<?php
$labels = array();
$labels['plugin_manager_title'] = 'Upravitelj vtičnikov';
$labels['plugin_manager_desc'] = 'Pregleda nameščene vtičnike Roundcube in preveri posodobitve.';
$labels['plugin'] = 'Vtičnik';
$labels['directory'] = 'Imenik';
$labels['enabled'] = 'Omogočeno';
$labels['disabled'] = 'Invalidi';
$labels['version_local'] = 'Lokalna različica';
$labels['version_remote'] = 'Najnovejša različica';
$labels['status'] = 'Status';
$labels['actions'] = 'Ukrepi';
$labels['unknown'] = 'neznano';
$labels['up_to_date'] = 'Ažurno';
$labels['update_available'] = 'Posodobitev je na voljo';
$labels['not_checked'] = 'Ni preverjeno';
$labels['refresh'] = 'Osvežitev';
$labels['toggle_remote'] = 'Omogočite oddaljeno preverjanje';
$labels['disable_remote'] = 'Onemogočite oddaljeno preverjanje';
$labels['enable_remote'] = 'Omogočite oddaljeno preverjanje';
$labels['remote_off_notice'] = 'Oddaljeni pregledi so onemogočeni!';
$labels['sources'] = 'Viri';
$labels['packagist'] = 'Packagist';
$labels['github'] = 'GitHub';
$labels['pm_yes'] = 'Da';
$labels['pm_no'] = 'Ne';
$labels['updateall'] = 'Posodobitev vseh vtičnikov';
?>
