<?php
$labels = array();
$labels['plugin_manager_title'] = 'Eklenti Yöneticisi';
$labels['plugin_manager_desc'] = 'Yüklü Roundcube eklentilerini inceler ve güncellemeleri kontrol eder.';
$labels['plugin'] = 'Eklenti';
$labels['directory'] = 'Rehber';
$labels['enabled'] = 'Etkin';
$labels['disabled'] = 'Engelli';
$labels['version_local'] = 'Yerel versiyon';
$labels['version_remote'] = 'En son sürüm';
$labels['status'] = 'Durum';
$labels['actions'] = 'Eylemler';
$labels['unknown'] = 'bilinmiyor';
$labels['up_to_date'] = 'Güncel';
$labels['update_available'] = 'Güncelleme mevcut';
$labels['not_checked'] = 'Kontrol edilmedi';
$labels['refresh'] = 'Yenile';
$labels['toggle_remote'] = 'Uzaktan kontrolleri etkinleştirin';
$labels['disable_remote'] = 'Uzaktan kontrolleri devre dışı bırak';
$labels['enable_remote'] = 'Uzaktan kontrolleri etkinleştirin';
$labels['remote_off_notice'] = 'Uzaktan kontroller Devre Dışı!';
$labels['sources'] = 'Kaynaklar';
$labels['packagist'] = 'Packagist';
$labels['github'] = 'GitHub';
$labels['pm_yes'] = 'Evet';
$labels['pm_no'] = 'Hayır';
$labels['updateall'] = 'Tüm Eklentileri Güncelleyin';
?>
