<?php
$labels = array();
$labels['plugin_manager_title'] = 'Quản lý plugin';
$labels['plugin_manager_desc'] = 'Kiểm tra các plugin Roundcube đã cài đặt và kiểm tra xem có bản cập nhật nào không.';
$labels['plugin'] = 'Plugin';
$labels['directory'] = 'Thư mục';
$labels['enabled'] = 'Đã bật';
$labels['disabled'] = 'Người khuyết tật';
$labels['version_local'] = 'Phiên bản địa phương';
$labels['version_remote'] = 'Phiên bản mới nhất';
$labels['status'] = 'Trạng thái';
$labels['actions'] = 'Hành động';
$labels['unknown'] = 'không rõ';
$labels['up_to_date'] = 'Cập nhật';
$labels['update_available'] = 'Có bản cập nhật sẵn sàng';
$labels['not_checked'] = 'Chưa được kiểm tra';
$labels['refresh'] = 'Làm mới';
$labels['toggle_remote'] = 'Bật tính năng kiểm tra từ xa';
$labels['disable_remote'] = 'Vô hiệu hóa kiểm tra từ xa';
$labels['enable_remote'] = 'Bật tính năng kiểm tra từ xa';
$labels['remote_off_notice'] = 'Kiểm tra từ xa đã bị vô hiệu hóa!';
$labels['sources'] = 'Nguồn';
$labels['packagist'] = 'Packagist';
$labels['github'] = 'GitHub';
$labels['pm_yes'] = 'Đúng';
$labels['pm_no'] = 'Không';
?>
