<?php
$labels = array();
$labels['plugin_manager_title'] = '插件管理器';
$labels['plugin_manager_desc'] = '检查已安装的 Roundcube 插件并检查更新。';
$labels['plugin'] = '插件';
$labels['directory'] = '目录';
$labels['enabled'] = '已启用';
$labels['disabled'] = '残疾';
$labels['version_local'] = '本地版本';
$labels['version_remote'] = '最新版本';
$labels['status'] = '现状';
$labels['actions'] = '行动';
$labels['unknown'] = '未知';
$labels['up_to_date'] = '最新';
$labels['update_available'] = '可更新';
$labels['not_checked'] = '未检查';
$labels['refresh'] = '刷新';
$labels['toggle_remote'] = '启用远程检查';
$labels['disable_remote'] = '禁用远程检查';
$labels['enable_remote'] = '启用远程检查';
$labels['remote_off_notice'] = '远程检查已禁用！';
$labels['sources'] = '资料来源';
$labels['packagist'] = '包装专家';
$labels['github'] = 'GitHub';
$labels['pm_yes'] = '是';
$labels['pm_no'] = '没有';
$labels['updateall'] = '更新所有插件';
?>
